image: Visual Studio 2017 RC
version: 1.0.{build}
build_script:
- npm install -g bower
- npm install -g gulp
- npm --version
- bower -version
- gulp --version
- ps: ./RunCodeFormatter.ps1
- ps: ./build.ps1
- ps: ./appveyor-packageweb.ps1
after_build:
- ps:  Push-AppveyorArtifact src/Nether.Web/bin/Release/netcoreapp1.1/Nether.Web.zip -FileName Nether.Web.Zip -Type WebDeployPackage
test_script:
- ps: ./run-unit-tests.ps1
